# Generated by Django 5.0.1 on 2024-01-20 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="test",
            new_name="text",
        ),
    ]
