# Generated by Django 5.0.1 on 2024-01-20 02:07

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0002_rename_test_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
